version: '3.8'

networks:
  postgres:
    driver: bridge
services:
  postgres:
    image: postgres
    networks:
      - postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "wedding"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"